services:
  dst-master:
    container_name: dst-master
    stop_signal: SIGKILL
    build:
      context: ./image
    image: dst-server:latest
    environment:
      CLUSTER_NAME: MyDediServer
      SERVER_TYPE: Master
    volumes:
      - "dst-data:/root/.klei/DoNotStarveTogether"
    networks:
      dst-network:
        ipv4_address: 172.25.0.2
    stdin_open: true
    tty: false

  dst-caves:
    container_name: dst-caves
    stop_signal: SIGKILL
    image: dst-server:latest
    environment:
      CLUSTER_NAME: MyDediServer
      SERVER_TYPE: Caves
    volumes:
      - "dst-data:/root/.klei/DoNotStarveTogether"
    networks:
      dst-network:
        ipv4_address: 172.25.0.3
    depends_on:
      - dst-master
    stdin_open: true
    tty: false

volumes:
  dst-data:
    name: "dst-data"

networks:
  dst-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
        - gateway: 172.25.0.1
