FROM steamcmd/steamcmd:latest

ARG BRANCH

RUN steamcmd +login anonymous +app_update 380870 -beta ${BRANCH} validate +quit \
  ||steamcmd +login anonymous +app_update 380870 -beta ${BRANCH} validate +quit \
  ||steamcmd +login anonymous +app_update 380870 -beta ${BRANCH} validate +quit

WORKDIR /root

COPY ./entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

# ENTRYPOINT [ "/bin/bash", "-c", "/bin/bash" ]
ENTRYPOINT [ "./entrypoint.sh" ]
