ARG JAVA_VERSION

FROM sapmachine:${JAVA_VERSION}

ARG MINECRAFT_VERSION
ARG FORGE_VERSION

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*

# Install Forge server
RUN mkdir -p /opt/Minecraft/image
RUN curl -L -o /opt/Minecraft/image/forge-installer.jar https://maven.minecraftforge.net/net/minecraftforge/forge/${MINECRAFT_VERSION}-${FORGE_VERSION}/forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-installer.jar
RUN cd /opt/Minecraft/image && java -jar forge-installer.jar --installServer && echo "eula=true" > eula.txt

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 25565/tcp
EXPOSE 24464/udp

ENTRYPOINT [ "/entrypoint.sh" ]
